sudo: true
language: haskell

branches:
  only:
  - master

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal"

matrix:
  include:
  - ghc: 8.10.1
  - ghc: 8.8.3
  - ghc: 8.6.5
  - ghc: 8.4.4
  - ghc: 8.2.2
  - ghc: 8.0.2

install:
  - |
    ghc --version
    cabal --version
    cabal new-update
    cabal new-build --enable-tests --enable-benchmarks

notifications:
  email: false
